### ISSUE TITLE
Colors[value] returns wrong color value

### ISSUE THREAD

**Issue by ghost** [danguilherme/uno#15]
When running this test code:
```typescript
const { Game, Values, Colors } = require('uno-engine');
const players = ['Player 1', 'Player 2']; 
let game = new Game(players);
let player = game.currentPlayer;
let wildCard;
while((wildCard = player.getCardByValue(Values['WILD_DRAW_FOUR'])) == undefined){
	game = new Game(players);
	player = game.currentPlayer;
}
wildCard.color = Colors['RED'];
game.play(wildCard);
let nextCard;
let i = 0;
while(i < player.hand.length && Colors[(nextCard = player.hand[i++]).color] != 'RED');
if(i >= player.hand.length){
	console.error("Did not reach card");
}
console.log(nextCard);
game.play(nextCard);
```

It will never reach the game.play(nextCard); line, as Colors[value] returns the value + 1.
When adding a -1 after color in the last loop, you will see, an error similar to this one:
```
Error: NO_COLOR 14, from discard pile, does not match 2 5
    at Game.play (F:\web\Test\node_modules\uno-engine\dist\game.js:172:19)
    at Object.<anonymous> (F:\web\Test\start.js:26:6)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```
Stating that the Wild Card color has been set to NO_COLOR.

PS: I messed up the code tags somehow.
PSPS: Adding a getCardFromColor function would be nice in some cases.

**Comment by Veith-Matthias** [comment]
To work around this issue I added '+ 1' to my code where I set the color and changed
` set color(color: Colors) {
    if (!this.isWildCard())
      throw new Error('Only wild cards can have theirs colors changed.');
    else if (color < 0 || color > 3)
      throw new Error('The color must be a value from Colors enum.');
    this._color = color;
  }`
to
`  set color(color: Colors) {
    if (!this.isWildCard())
      throw new Error('Only wild cards can have theirs colors changed.');
    else if (color < 0 || color > 4)
      throw new Error('The color must be a value from Colors enum.');
    this._color = color;
  }`

In the uno/src/card/card.ts file.

**Comment by danguilherme** [comment]
I believe you are focusing in a different problem here.
After `game.play(wildCard)`, the game automatically passes the turn, which makes `player` outdated with `game.currentPlayer`.

So when you look for a card that matches the color of the one in the discard pile, you are looking in the wrong hand (in the hand of the player that just discarded).

Also, after playing a wild draw four, the player must draw cards, so `game.play(nextCard);` will throw an error even if `game.currentPlayer` has the card in their hand.

[Running example.](https://runkit.com/danguilherme/5cdab88f15cc04001a0bb646)

<details>
<summary>Raw code</summary>

```typescript
const { Game, Values, Colors } = require('uno-engine');
const players = ['Player 1', 'Player 2']; 
let game = new Game(players);
let player = game.currentPlayer;
let wildCard;
while((wildCard = player.getCardByValue(Values['WILD_DRAW_FOUR'])) == undefined){
	game = new Game(players);
	player = game.currentPlayer;
}

wildCard.color = Colors['RED'];
game.play(wildCard);
// here, game.currentPlayer changes, so you should update the player variable:
player = game.currentPlayer;

let nextCard;
let i = 0;
while(i < player.hand.length && Colors[(nextCard = player.hand[i++]).color] != 'RED');
if(i >= player.hand.length){
	console.error("Did not reach card");
}
console.log(nextCard.toString());

// as a wild draw four card was played, player is required to draw, not play (game.draw()).
// This will correctly throw an exeption:
game.play(nextCard);
```

</details>

Please let me know if this fixes your problem.

**Comment by Veith-Matthias** [comment]
I isolated this problem from a project I am working on. Since there are only 2 players, it will skip the other player and go back to the current player. When looking at the discarded card you will see, that, when setting the color to red, the color ends up being NO_COLOR and all other colors are offset by -1. I couldn't narrow down my problem further so I wrote this small example to demonstrate what I could find.

**Comment by danguilherme** [comment]
Okay, I should have led with that: you are not using the npm version `0.0.3`, right?

The error is, along with other related parts, in [`Card#color`](https://github.com/danguilherme/uno/compare/feature/api-improvements#diff-12fd96a9f4248256d968decd465cad83L24). [`Card#toString()`](https://github.com/danguilherme/uno/compare/feature/api-improvements#diff-12fd96a9f4248256d968decd465cad83L78) is also returning a wrong value, as `color` is 0 (which is 'RED'), not undefined.

This is indeed a bug. You can try using [the last stable version](https://github.com/danguilherme/uno/releases/tag/v0.0.3) while a fix is not available for the `alpha` releases.

**Comment by Veith-Matthias** [comment]
I am using version 0.1.1-alpha. Thank you for lending me your time. I would leave it at that because if it ain't broke don't fix it.

**Comment by Guaxinim5573** [comment]
This error is in `src/deck.js` on line 27. `for` is getting numbers from 1 to 4. Change line 27 from this:
```for(let color = 1; color <= 4; color++) {```
To this:
```for(let color = 0; color < 4; color++) {```

**Comment by danguilherme** [comment]
Hello @Guaxinim5573, could you try installing the latest version of the package?
```bash
# npm
npm install uno-engine@1.0.3 --save

# yarn
yarn add uno-engine@1.0.3
```

**Comment by danguilherme** [comment]
Please install version 1.1.0 to have this fix.

```bash
# npm
npm install uno-engine@1.1.0 --save

# yarn
yarn add uno-engine@1.1.0
```
