### ISSUE TITLE
Create library usage documentation

### ISSUE THREAD

**Issue by Californ1a** [danguilherme/uno#2]
How do you use this? All the docs/readme are just game rules, not how to use the library. I can take some guesses from trial and error or by looking through the tests, but there really should be some docs.

Essentially what I'm trying to do is remake [this](https://pastebin.com/FHKFLXPj) really (really, really) old IRC uno script (which had some neat stuff like playing against the bot if no one else wanted to join, logins to save scores, etc.), but in js on Discord instead of IRC. It seems like you already have a lot of the core backend game mechanics for uno done, but none of the library is documented.

What I've pieced together so far, for my usage with node/npm, is
```js
const uno = require("uno-engine");
const players = ["Player 1", "Player 2", "etc"]; //10 max players
const game = uno.Game(players);
game.newGame();
```
I assume the next thing to do would be to query `game.discardedCard.toString()` to see what the current card in-play is (to display to the players), and also do something like this to display each player's hand to each of them
```js
const players = ["Player 1", "Player 2", "etc"]; //from above
//--
players.forEach(p => {
  const hand = game.getPlayer(p).hand.toString();
  //display hand to player
}
```
There should probably be a `game.players` or `game.getPlayers()` so you can get the full list of players without having to keep track of that list outside of the game, but maybe I'm just missing it. It would also be extremely useful if you could dynamically add/remove players mid-game, instead of having to initialize the game with the players already set. I will probably make a separate issue for feature requests though because there are quite a few things related to player control (removing afk/away players without completely starting a new game, for example) that would be nice to have.

-----

Anyway, from there it seems like playing a card is a little obtuse
```js
const args = //player's color and value in an array - ["blue","two"]
game.play(uno.Card(uno.Values[args[1].toUpperCase()], uno.Colors[args[0].toUpperCase()]));
```
It would be a lot nicer if you could just pass in the string, `game.play("blue two")` and have the library `.toUpperCase()` it and figure out the matching color/value properties and find the correct card. It just feels weird that that library itself isn't manging that matching. I've made this to make it easier for myself to use
```js
const getCard = (args) => {
  const c = (color[args[0].toUpperCase()]) ? color[args[0].toUpperCase()] : color[args[1].toUpperCase()];
  const v = (value[args[1].toUpperCase()]) ? value[args[1].toUpperCase()] : value[args[0].toUpperCase()];
  return uno.Card(v, c);
};
```

~~Also, I can't seem to get WD4 to work. I'm able to play it with `no_color` but providing a color throws the player doesn't have card error. This probably has something to do with my `getCard()` function, but I don't see what the issue could be. Ideally, I would be able to use `blue wild_draw_four` or `green wild` (dumping the hands into public chat for testing): https://i.imgur.com/eWc1GCu.png~~

All I needed to do was change the above to this, which got wild and wd4 working, though I do now have to pass in the player

```js
const getCard = (args, p) => {
  const c = (color[args[0].toUpperCase()]) ? color[args[0].toUpperCase()] : color[args[1].toUpperCase()];
  const v = (value[args[1].toUpperCase()]) ? value[args[1].toUpperCase()] : value[args[0].toUpperCase()];
  let card = uno.Card(v, c);
  if (args.includes("wild") || args.includes("wild_draw_four")) {
    card = p.getCardByValue(v);
    card.color = color.get(c);
  }
  return card;
};
```

This should really be much more intuitive. You should be able to play `no_color` cards with any color without having to manually assign that color to the card in the player's hand before playing it. The library should know if you play `blue wild` that you want to play a `no_color wild` and make it blue.

-----
I seem to have an issue with dt and wd4 cards. They will automatically draw all *except one* card, which has to be drawn manually by the player on their "turn" even though dt and wd4 are supposed to skip them. Playing a dt or wd4 doesn't let the next player actually play any card, they can only draw, but that draw should be automatic. It also automatically passes them after they draw. These two cards should function the same as skip and (in a 2-player game) reverse, where the skipped person doesn't get set as the current player. The draws should be automatic and set the next person as current.

Also, if you play a card that can't be played, it should return an error, so you can tell players they didn't play a suitable card.

Here's a [gist](https://gist.github.com/Californ1a/3170202cd5182a300a381b810560ade6) of my testing file

By the end of writing this out, I believe I've mostly figured out the library, but there still should be docs somewhere.

**Comment by danguilherme** [comment]
Thank you for this! I've created this lib with future intentions, but that future is still to come, so I never documented it or fully tested its API. I really appreciate your feedback (keep them coming!).

I've created a small CLI game using this library, and it could help you while there's no official documentation: https://github.com/danguilherme/uno-cli/blob/master/index.js.

**`game.players`**
It really doesn't exist... I remember thinking about that, but I was afraid the library user would modify the array outside of the game. I really don't know why I didn't think of cloning the array before returning it to the user. Anyway, it would be necessary to implement (very simple, though).

**add/remove players mid-game**
That would be a more complex feature, but that would be a good addition.

**`getCard`**
In the client I linked above, I've also created a [function to build cards from string](https://github.com/danguilherme/uno-cli/blob/af3efc0ead0d9494fff9afe72586007bb40ca62c/index.js#L192-L198). I tried to let the lib as "tied" as possible, it was a design choice to receive only a `Card` object in the `play` function.

But at that time I was the only user of the lib, this may be improved.

**Can't play `WILD_DRAW_FOUR`**
You have to [set the card color](https://github.com/danguilherme/uno-cli/blob/af3efc0ead0d9494fff9afe72586007bb40ca62c/index.js#L157-L163) before discarding it.
If the player could discard a card by string, sure it would be easier: the lib would automatically set the card color then play it.

I would think of a helper method building `Card` objects from strings, not `game.play` itself. What do you think?

**Issue with `DRAW_TWO` and `WILD_DRAW_FOUR`**
> They will automatically draw all *except one* card [...]

I don't remember having this issue in the CLI, would have to dig in -- but it should be working fine.

> [...] which has to be drawn manually by the player on their "turn" even though dt and wd4 are supposed to skip them.

If you play a `DRAW_TWO`, the next player could play a matching `DRAW_TWO` **or** he will have to `draw`, receiving 2 cards (or the amount multiplied by the number of discarded DRAW_TWO in a row) - only then [he loses his turn](https://github.com/danguilherme/uno/blob/4c60847fc192757be96344c6e7e030add5a2b332/game.js#L121-L124). That's one reason why he doesn't loses his turn right away.

If this is a rule specific to your game, you could listen to the `cardplay` event and set `game.currentPlayer` to the `game.nextPlayer`, depending on the discarded card.

As you can see, the idea is to let a little room for lib users to customize the gameplay, as Uno has a lot of rules you may or may not consider when playing.

**Wrong card played**
> Also, if you play a card that can't be played, it should return an error, so you can tell players they didn't play a suitable card.

[It is supposed to be throwing an error.](https://github.com/danguilherme/uno/blob/master/game.js#L151-L152)

---

I wish it's clearer now for you. I am more than happy to improve the API, to make the lib more intuitive and easy to use -- the repo is open to feature requests.

If you need anything, or have any more ideas, do tell.

**Comment by Californ1a** [comment]
If you haven't seen, I did send a PR #3 to modify the readme with some documentation. It's still missing some of the functionality as noted in the PR, but you can have a look at the new readme on my fork: https://github.com/Californ1a/uno/blob/master/README.md

>I've created a small CLI game using this library, and it could help you while there's no official documentation: https://github.com/danguilherme/uno-cli/blob/master/index.js. [...]
>[...] I've also created a [function to build cards from string](https://github.com/danguilherme/uno-cli/blob/af3efc0ead0d9494fff9afe72586007bb40ca62c/index.js#L192-L198).

I have seen that and did some looking through that as well when I was writing the PR. I also saw your function to convert string to card.

The problem I have with that function was that the color and value has to be in a specific order. With the one I provided, the order doesn't matter. You can pass in either `["blue", "six"]` or `["six", "blue"]` and both will get you the card. This is essential when taking user input and you may not know what order the user is going to put in the arguments. It makes more sense if the program can figure out the correct card from either order instead of requiring the user to know the *correct* order.

That said, the `getCard()` function I provide as an example in the PR documentation does require a specific order as well, and doesn't `toUpperCase()` the args, though it is meant as just a simple example. Ideally, I think the best way to deal with it, if included in the lib, would be like this:
```js
const getCard = (args, player) => {
  args[0] = args[0].toUpperCase();
  args[1] = args[1].toUpperCase();
  const c = (Colors.get(args[0])) ? Colors.get(args[0]) : Colors.get(args[1]);
  const v = (Values.get(args[1])) ? Values.get(args[1]) : Values.get(args[0]);
  let card = Card(v, c);
  if (args.includes("WILD") || args.includes("WILD_DRAW_FOUR")) {
    card = player.getCardByValue(v);
    card.color = color.get(c);
  }
  return card;
};
```
However, if it is included as part of the lib, I don't think you should have to pass in the player, and it should deal with the wild/wd4 outside of this function, probably within the `Card(value, color)` - you should be able to pass a color alongside the value of wild/wd4, and be able to play a no_color wild/wd4 from a player's hand with any wild/wd4 color given, instead of setting the color of the card in the player's hand.

>If you play a DRAW_TWO, the next player could play a matching DRAW_TWO or he will have to draw, receiving 2 cards (or the amount multiplied by the number of discarded DRAW_TWO in a row) - only then he loses his turn. That's one reason why he doesn't loses his turn right away.

I don't think this is actually part of uno's rules. I've always played with dt and wd4 being automatic (aside from [wd4's "challenge" rule](https://gamefaqs.gamespot.com/boards/975337-uno/54304378#2), which doesn't seem to be implemented yet). On your current readme, all it says about dt is `When a person places this card, the next player will have to pick up two cards and forfeit his/her turn.` and wd4 doesn't mention this behavior either. Even on https://www.unorules.com/ for dt it says the same as in your readme, and under `Two Player & Four Player Rules` near the bottom it says:
>If you play a Draw Two or Wild Draw Four card, your opponent has to draw the number of cards required, and then play immediately resumes back on your turn.

I can't find this dt rule, where you're able to play another dt after someone else and then not draw cards, anywhere. However, if the intention is to allow these kinds of "house rules" I think the better solution would be to pass in an `options` object when starting a new game.

>Wrong card played
>[It is supposed to be throwing an error.](https://github.com/danguilherme/uno/blob/master/game.js#L151-L152)

Ah, that's my bad then. I got it now. It works and throws the error, I just forgot to catch it.

**Comment by danguilherme** [comment]
I did see the PR - just approved it, thanks!

`getCard` functionality would sure be a good addition, and once inside the `game` instance, it would not be necessary to send the player (as we would have `game.currentPlayer`).
I still don't know how to implement it though. Maybe `play` could be overloaded: `play(Card)` or `play(color, value)` (where `color` and `value` may be swapped with no problems).

You're right, this `DRAW_TWO` rule is not official. What is curious is that in every circle I played Uno around here, this rule isn't even discussed - it's always there.
I'll check to change this behavior and see a way to customize it on the CLI. I don't know if an `options` object is a good idea, as there's a lot of house rules existing and it could make the code very confusing, deviating from the official rules.
Maybe this could be achieved with a better use of events, and anyone that wants to add rules outside of the official ones, will implement them.

**Comment by Californ1a** [comment]
>I don't know if an options object is a good idea, as there's a lot of house rules existing and it could make the code very confusing, deviating from the official rules.
Maybe this could be achieved with a better use of events, and anyone that wants to add rules outside of the official ones, will implement them.

Maybe repurpose the `cardplay` event, so that it fires when a card is played but *before it gets placed in the discard pile* (and include both the card played and the current discard card in the arguments), so anyone using the lib has the ability to intercept card plays and inject their own house rules before each card gets placed. You already have the `nextplayer` event, which fires directly after `cardplay` and could include the newly placed card in the arguments, to (mostly) replace the need for the current `cardplay` event.

This would probably require some additional lib functionality as well so that you would have the ability to prevent certain lib actions like automatically moving to the next player or automatically drawing cards.
