### ISSUE TITLE
Error when playing wild card 4

### ISSUE THREAD

**Issue by nikhilbaby** [danguilherme/uno#23]
Please check the screenshot to get more details about the issue:

![image](https://user-images.githubusercontent.com/9347673/67364938-341d3000-f58e-11e9-846a-ed74f1bd5dc9.png)

When I played the wild card 4, it shows me:
`Error: Card must have its color set before playing`

On checking, I found that the game.play has the following code in `game.js`

```
        if (card.color == undefined)
            throw new Error('Card must have its color set before playing');
        // check if the played card matches the card from the discard pile...
        
```

How should I play the wild card 4? Please advise on this.

**Comment by nikhilbaby** [comment]
I was able to resolve the issue.  Thanks.

**Comment by danguilherme** [comment]
Glad you solved it!
Yes, you need to set the wild card color before playing it, just like in real life, to proceed the game with that color.

You can also create cards in a clearer way, by using the `Values` enum (instead of using "magic numbers", like `14`):

```js
const { Game, Card, Values, Colors } = require('uno-engine');

// ...

const cardToPlay = Card(Values.get("WILD_DRAW_FOUR"));

// set color
cardToPlay.color = Colors.get("RED");

// and only then play it
game.play(cardToPlay);
```

For more information you can check the [Card Properties section in the Readme](https://github.com/danguilherme/uno/tree/v0.0.3#card-properties).

**Comment by nikhilbaby** [comment]
Thanks for the help. I'm creating a web application that used express API's and socket to play the game. The values are transformed in the front end with Values and Colors in the front end and hence using the numbers.

When playing wild cards, I was creating card like this:

```
let card = new Card(14)
card.color = 1

```

This was throwing errors for game.play()

I was able to resolve this with:

```
let card = game.currentPlayer.getCardByValue(14);
card.color = 1
```

Another doubt that I have is about `game.uno() `. Will the players penalized for not calling Uno in the game.  How does this work?

**Comment by danguilherme** [comment]
You should always use the already created cards, you should not create cards yourself.

When using `game.play()`, the game will check if `currentPlayer` has the given card at hand, and throw the card instance from the player's hand. So your last example is how it should be done.

---

About `game.uno()`, the player will be penalised as appropriate, [here's the logic](https://github.com/danguilherme/uno/tree/e4a631d2a60adb546b49f4dbd4e3365a60b6a339#game-loop):

```js
// Yelling UNO!
game.uno();           // game.currentPlayer is yelling UNO!

game.uno("Player 1"); // Other than current player yells UNO (in this case, "Player 1"
                      // - If the yelling player is the current player,
                      //   and they have 2 or less cards, he is just marked as "yelled"
                      // - If the yelling player has more than 2 cards,
                      //   the game searches for someone with 1 card that did not yell "UNO!",
                      //   and make him draw 2 cards. If there's no one,
                      //   the yelling player draws instead.
```

With this said, let's create some scenarios:

**SCENARIO 1**
Yelling UNO with no penalties, having 2 or less cards at hand.
```
> Player 1 has 2 cards at hand
> Player 2 has 5 cards at hand

> It's Player 1 turn
	For yelling UNO, this doesn't matter, just keeping it here for illustration

> Player 1 yells UNO
	Somehow on your UI would have a way to do this.
	When this happens, you'd call game.uno("Player 1")
> Player 1 plays his card.

> Game changes turn to Player 2

> End of this scenario
```

**SCENARIO 2**
Opposing player yells UNO when the other one didn't.
```
> Player 1 has 1 card at hand
> Player 2 has 5 cards at hand

> It's Player 1 turn

> Player 2 yells UNO
	game.uno("Player 2")

> Game draws 2 cards into Player 1 hand
	Notice that Player 1 didn't yell UNO

> End of this scenario
```

**SCENARIO 3**
Opposing player yells UNO for no valid reason.
```
> Player 1 has 5 cards at hand
> Player 2 has 5 cards at hand

> It's Player 1 turn

> Player 2 yells UNO

> Game draws 2 cards into Player 2 hand
	There was no player with 2 or less cards at hand, so the yelling player is penalised for the "false alarm"

> End of this scenario
```

**Comment by danguilherme** [comment]
What version of the package are you using?

**Comment by nikhilbaby** [comment]
I'm using `0.1.1-alpha`. Thanks a lot for the detailed explanation of the cases. I could never have figured it out without your help.

**Comment by nikhilbaby** [comment]
Can you also help me with https://github.com/danguilherme/uno/issues/24

I'm not using the numerical representation of the card values and colors. It looks like you have colors from 0 to 3 in `/src/card/colors.ts` but when we look at the hands of the players you can see that there are values from 1 to 4. 

This will have an effect when we try to assign color 4 to a wild card.

**Comment by danguilherme** [comment]
One tip is to read the [test cases](https://github.com/danguilherme/uno/blob/master/test/game.ts#L259) when in doubt. There's not much of them, but generally they give a good idea on how things should work.

(Of course having proper documentation would be even better, but it's not complete at the moment.)
