### ISSUE TITLE
Make deck accessible

### ISSUE THREAD

**Issue by filipemeneses** [danguilherme/uno#8]
There isn't a getter for `drawPile`, a method `getDeck` would do the trick

**Comment by danguilherme** [comment]
Would you mind to explain what is your use case exactly?

**Comment by filipemeneses** [comment]
I want to see which cards are still available in the deck. The `drawPile` is only accessible in the lib scope. I can't get that pile of cards using as a npm package

**Comment by filipemeneses** [comment]
I found a way to do it without knowing the deck data. It is to check the probabilistics based on the current deck. A cheater AI player

**Comment by filipemeneses** [comment]
So, what is going to be?

**Comment by danguilherme** [comment]
I will add a getter to the `drawPile` cards... but I don't know when these changes will go live.

**Comment by filipemeneses** [comment]
Why not publish as `0.0.3`? since this enhancement won't break the public API, together with #9

**Comment by danguilherme** [comment]
Version 0.1.0 is intended to go out with the first user requests.

**Comment by danguilherme** [comment]
Solved oncommit [eebb799](https://github.com/danguilherme/uno/commit/eebb799c834ef1797d9ed5b82dc0c4a759736164 "Add `players` and `deck` (draw pile) accessors").
